apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: hostpath

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    env:
    - name: author
      value: shark
    volumeMounts:
    - name: data
      mountPath: /app
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: testpvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
