apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
spec:
  type: NodePort
  selector:
    app: zabbixserver
  ports:
  - port: 10051
    targetPort: 10051
    nodePort: 30051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbixserver
  template:
    metadata:
      labels:
        app: zabbixserver
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10051
        readinessProbe:
          tcpSocket:
            port: 10051
          initialDelaySeconds: 5
          periodSeonds: 10
        livenessProbe:
          tcpSocket:
            port: 10051
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: DB_SERVER_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "zabbix"
        - name: MYSQL_DATABASE
          value: "zabbix"
        - name: ZBX_CACHESIZE
          value: "512M"
        - name: ZBX_TRENDCACHESIZE
          value: "512M"
        - name: ZBX_HISTORYCACHESIZE
          value: "1024M"
        - name: ZBX_HISTORYINDEXCACHESIZE
          value: "1024M"
				- name: ZBX_STARTTRAPPERS
          value: "5"
				- name: ZBX_STARTPREPROCESSORS
          value: "10"
				- name: ZBX_STARTDBSYNCERS
          value: "10"
				- name: DB_SERVER_PORT
          value: "3306"
      - name: zabbix-agent
        image: zabbix/zabbix-agent
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10050
        env:
        - name: ZBX_HOSTNAME
          value: "Zabbix Server"
        - name: ZBX_SERVER_HOST
          value: "127.0.0.1"
        - name: ZBX_PASSIVE_ALLOW
          value: "true"
        - name: ZBX_STARTAGENTS
          value: "3"
        - name: ZBX_TIMEOUT
          value: '10'
        securityContext: 
          privileged: true
